title: Beissinger Lab
description: Website for the Beissinger Lab

url: http://beissingerlab.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Research
   url: /about
 - title: People
   url: /contact

social:
   github: timbeissinger
   twitter: timbeissinger
   email: timbeissinger@gmail.com

google_analytics: 
