# Site settings
title: Beissinger Lab
email: timbeissinger@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Website for the Beissinger Lab
#baseurl: " " # the subpath of your site, e.g. /blog/
url: "http://beissingerlab.github.io" # the base hostname & protocol for your site
twitter_username: timbeissinger
github_username: timbeissinger

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]